package sqlg2.db;

import java.util.ArrayList;
import java.util.List;

/**
 * This class used for OUT parameters of cursor types.
 *
 * @param <T> row type class to return from cursor
 */
public final class TypedList<T> {

    /**
     * Row type class to which cursor will be mapped. It will be generated by preprocessor.
     */
    public final Class<T> cls;
    /**
     * List to collect results from cursor
     */
    public final List<T> list;
    /**
     * true if extract only meta-info from cursor
     */
    public final boolean meta;

    /**
     * Constructor for non-meta instance.
     */
    public TypedList(Class<T> cls) {
        this(cls, false);
    }

    public TypedList(Class<T> cls, boolean meta) {
        this.cls = cls;
        this.list = new ArrayList<T>();
        this.meta = meta;
    }
}
