-- Create user in Oracle:
-- CREATE USER sqlg2 IDENTIFIED BY sqlg2;
-- GRANT CONNECT, RESOURCE TO sqlg2;
-- CONNECT sqlg2/sqlg2;

CREATE TABLE EMP (
  EMP_NO     DECIMAL(4) NOT NULL,
  EMP_NAME   VARCHAR(10) NOT NULL,
  JOB        VARCHAR(9),
  MGR        DECIMAL(4),
  HIRE_DATE  DATE
)
/

INSERT INTO EMP (EMP_NO, EMP_NAME, JOB, HIRE_DATE) VALUES (1, 'SCOTT', 'ANALYST', CURRENT_DATE)
/

CREATE SEQUENCE EMP_SEQ INCREMENT BY 1 START WITH 10
/

CREATE OR REPLACE TRIGGER EMP_BI BEFORE INSERT ON EMP FOR EACH ROW
BEGIN
  IF :NEW.EMP_NO IS NULL THEN
    SELECT EMP_SEQ.NEXTVAL INTO :NEW.EMP_NO FROM DUAL;
  END IF;
END;
/

CREATE TYPE T_USEROBJ AS OBJECT (
  ID DECIMAL(12),
  NAME VARCHAR(20)
);
/

CREATE TABLE OBJUSERS (
  USEROBJ T_USEROBJ
)
/

INSERT INTO OBJUSERS (USEROBJ) VALUES (T_USEROBJ(1, 'SCOTT'))
/

INSERT INTO OBJUSERS (USEROBJ) VALUES (T_USEROBJ(2, 'KING'))
/

CREATE OR REPLACE PACKAGE RS_PACK AS
  TYPE t_rs IS REF CURSOR;

  PROCEDURE RS_TEST(p_cur OUT t_rs);
END;
/

CREATE OR REPLACE PACKAGE BODY RS_PACK AS
  PROCEDURE RS_TEST(p_cur OUT t_rs) IS
  BEGIN
    OPEN p_cur FOR SELECT * FROM EMP;
  END;
END;
/
