-- Create user in PostgreSQL:
-- CREATE USER sqlg2 PASSWORD 'sqlg2';
-- CREATE SCHEMA AUTHORIZATION sqlg2;
-- CREATE DATABASE sqlg2 OWNER sqlg2;

CREATE TABLE EMP (
  EMP_NO     DECIMAL(4) NOT NULL,
  EMP_NAME   VARCHAR(10) NOT NULL,
  JOB        VARCHAR(9),
  MGR        DECIMAL(4),
  HIRE_DATE  DATE
);

INSERT INTO EMP (EMP_NO, EMP_NAME, JOB, HIRE_DATE) VALUES (1, 'SCOTT', 'ANALYST', CURRENT_DATE);

CREATE SEQUENCE EMP_SEQ INCREMENT BY 1 START WITH 10;

ALTER TABLE EMP ALTER COLUMN EMP_NO SET DEFAULT nextval('emp_seq');
