CREATE TABLE INTEST (
  VAL DECIMAL(3)
);

CREATE TABLE USERS (
  ID   DECIMAL(12) NOT NULL PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL
);

INSERT INTO USERS (ID, NAME) VALUES (1, 'SCOTT');

INSERT INTO USERS (ID, NAME) VALUES (2, 'KING');

CREATE TABLE CONFIG (
  USER_ID DECIMAL(10),
  ROLE_ID DECIMAL(10)
);
